### ISSUE TITLE
[FEAT] :sparkles: Add docker

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-admin#21]
### Description

we need to configure docker as it's configured in frontend repo

**Comment by leonardonatali** [comment]
Hi!I would like to work on this!

**Comment by aayushchugh** [comment]
@leonardonatali go ahead but please remember to copy config from [frontend repo](https://github.com/MultiEmail/frontend)

and server should work on port `5000`

**Comment by aayushchugh** [comment]
@leonardonatali Someone else from our team is working on this : )
