### ISSUE TITLE
[FEAT] :sparkles: 404 page

### ISSUE THREAD

**Issue by Tchakoumi** [MultiEmail/MultiEmail-admin#24]

**Comment by Tchakoumi** [comment]
Add a 404 page to the admin app

**Comment by is-it-ayush** [comment]
Thank you for the suggestion! Do you want to take up this issue @Tchakoumi?

**Comment by Tchakoumi** [comment]
yeah. asign it to me. I'll get to it by the end of the day

**Comment by aayushchugh** [comment]
@Tchakoumi assigned you
