### ISSUE TITLE
[FEAT] :sparkles: create UI for `/users` page

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/MultiEmail-admin#92]
### Description

all the logic part is implemented only UI needs to get worked upon

### Anything else?

take table UI reference from [tailwind docs](https://tailwindcss.com/docs/table-layout)

**Comment by JohnnyOhms** [comment]
Assign me to this issue, pls give more details on what to implement on the UI for users page

**Comment by aayushchugh** [comment]
@JohnnyOhms you just need to create a table like this

![image](https://user-images.githubusercontent.com/69336518/209053413-f04b7f2d-d72f-4dc7-9595-c31df27175f0.png)
you can take layout reference from this

logic to fetch users from API is already implemented

**Comment by JohnnyOhms** [comment]
Ok, am working on it sir
